//! Pack index parsing against indexes generated by Git.

use std::path::{Path, PathBuf};
use std::{fs, process::Command};
use tempfile::TempDir;
use zerogit::objects::pack::PackIndex;
use zerogit::{Error, Oid, Repository};

fn git(dir: &Path, args: &[&str]) -> Vec<u8> {
    let output = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .env(
            "GIT_CONFIG_GLOBAL",
            if cfg!(windows) { "NUL" } else { "/dev/null" },
        )
        .env("GIT_CONFIG_NOSYSTEM", "1")
        // Background auto-maintenance would repack concurrently with the test.
        .env("GIT_CONFIG_COUNT", "2")
        .env("GIT_CONFIG_KEY_0", "maintenance.auto")
        .env("GIT_CONFIG_VALUE_0", "false")
        .env("GIT_CONFIG_KEY_1", "gc.auto")
        .env("GIT_CONFIG_VALUE_1", "0")
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    output.stdout
}

/// Creates a repository whose objects are all in one pack; returns the pack path.
fn packed_repository() -> (TempDir, Repository, PathBuf) {
    let temp = TempDir::new().unwrap();
    let repo = Repository::init(temp.path()).unwrap();
    for i in 0..20 {
        let name = format!("dir{}/file{}.txt", i % 3, i);
        fs::create_dir_all(temp.path().join(format!("dir{}", i % 3))).unwrap();
        fs::write(
            temp.path().join(&name),
            format!("line\n{}\n", i).repeat(i + 1),
        )
        .unwrap();
        repo.add(&name).unwrap();
        repo.create_commit(&format!("Commit {}", i), "Test", "test@example.com")
            .unwrap();
    }
    git(temp.path(), &["repack", "-a", "-d"]);
    let pack_dir = repo.git_dir().join("objects/pack");
    let pack = fs::read_dir(&pack_dir)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .find(|path| path.extension().is_some_and(|ext| ext == "pack"))
        .unwrap();
    (temp, repo, pack)
}

/// Parses `git show-index` output into (oid, offset, crc32) rows.
fn show_index(dir: &Path, idx: &Path) -> Vec<(Oid, u64, u32)> {
    let output = Command::new("git")
        .arg("-C")
        .arg(dir)
        .arg("show-index")
        .stdin(fs::File::open(idx).unwrap())
        .output()
        .unwrap();
    assert!(output.status.success());
    String::from_utf8(output.stdout)
        .unwrap()
        .lines()
        .map(|line| {
            let mut fields = line.split_whitespace();
            let offset = fields.next().unwrap().parse().unwrap();
            let oid = Oid::from_hex(fields.next().unwrap()).unwrap();
            let crc = fields
                .next()
                .unwrap()
                .trim_matches(|c| c == '(' || c == ')');
            (oid, offset, u32::from_str_radix(crc, 16).unwrap())
        })
        .collect()
}

#[test]
fn git_generated_index_matches_show_index() {
    let (temp, _repo, pack) = packed_repository();
    let idx = pack.with_extension("idx");
    let index = PackIndex::read(&idx).unwrap();

    let mut expected = show_index(temp.path(), &idx);
    expected.sort_by_key(|(oid, _, _)| *oid);
    assert!(expected.len() > 60);
    let actual: Vec<_> = index
        .entries()
        .iter()
        .map(|entry| (entry.oid, entry.offset, entry.crc32))
        .collect();
    assert_eq!(actual, expected);

    for (oid, offset, crc32) in &expected {
        let entry = index.get(oid).unwrap();
        assert_eq!((entry.offset, entry.crc32), (*offset, *crc32));
        assert_eq!(
            index.find_objects_by_prefix(&oid.to_hex()).unwrap(),
            vec![*oid]
        );
    }

    let pack_bytes = fs::read(&pack).unwrap();
    assert_eq!(
        index.pack_checksum()[..],
        pack_bytes[pack_bytes.len() - 20..]
    );
}

#[test]
fn git_generated_v1_index_is_unsupported() {
    let (temp, _repo, pack) = packed_repository();
    // Relative names avoid passing Windows verbatim (\\?\) paths to Git.
    let pack_name = pack.file_name().unwrap().to_str().unwrap();
    git(
        &temp.path().join(".git/objects/pack"),
        &["index-pack", "--index-version=1", "-o", "v1.idx", pack_name],
    );
    assert!(matches!(
        PackIndex::read(pack.with_file_name("v1.idx")),
        Err(Error::UnsupportedPackIndexVersion(1))
    ));
}

#[test]
fn git_generated_index_rejects_corruption_without_panicking() {
    let (_temp, _repo, pack) = packed_repository();
    let data = fs::read(pack.with_extension("idx")).unwrap();

    let mut corrupt = data.clone();
    corrupt[2000] ^= 0x40;
    assert!(matches!(
        PackIndex::parse(&corrupt),
        Err(Error::InvalidPackIndex { .. })
    ));
    for len in (0..data.len()).step_by(7) {
        assert!(PackIndex::parse(&data[..len]).is_err());
    }
}
